# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "NamPNQ's Blog"
description: > # this means to ignore newlines until "email:"
   Thoughts, stories and ideas.

email: nampnq@gmail.com
#blog logo
logo: "//www.gravatar.com/avatar/7cf19173e360b0e328de258ea52c1f9a"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Nam Pham'
author: 'Nam Pham'
author_image: "//www.gravatar.com/avatar/7cf19173e360b0e328de258ea52c1f9a?s=250&amp;d=mm&amp;r=x"

paginate:	3

url: https://blog.nampnq.cf
enforce_ssl: blog.nampnq.cf
baseurl: ""
#used to display twitter cards
twitter_handle: '@nampnq'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/nampnq
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/nampnq
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
